### ISSUE TITLE
Consider allowing schemas from a local file

### ISSUE THREAD

**Issue by Amoenus** [grepbox/grepql#3]
As a registered grepQL user
I want to specify a file from a local file system when adding a new endpoint
So I can submit a schema for analysis without sharing authorization tokens

**Comment by kawamurakazushi** [comment]
@Amoenus 
thanks for opening an issue!

yes, actually we are currently working on this feature,
also to be able to pass headers on endpoint for protected APIs.

**Comment by kawamurakazushi** [comment]
@Amoenus 
I added support for local schema file.
Please give it a try!

![image](https://user-images.githubusercontent.com/7858158/103396223-4d980f80-4b75-11eb-9694-01a36c4ebcad.png)
